import { Recipe } from '@/types';

interface CuratedRecipe {
  name: string;
  description: string;
  tags: string[];
  ingredients: string[];
  instructions: string[];
  estimatedMacros: { calories: number; protein: number; carbs: number; fat: number; fiber?: number };
}

const CURATED: CuratedRecipe[] = [
  {
    name: 'Lemon-Garlic Baked Salmon with Roasted Sweet Potato',
    description: 'Sheet-pan dinner, ready in 30 minutes. Naturally gluten and dairy free.',
    tags: ['gluten-free', 'dairy-free', 'protein-rich', 'omega-3'],
    ingredients: [
      '2 salmon fillets (170 g each)',
      '1 large sweet potato, cubed',
      '2 tbsp olive oil',
      '1 lemon, half sliced + half juiced',
      '3 garlic cloves, minced',
      '1 tsp smoked paprika',
      'Salt and pepper',
      'Fresh parsley to finish',
    ],
    instructions: [
      'Preheat oven to 220 °C / 425 °F.',
      'Toss sweet-potato cubes with 1 tbsp olive oil, paprika, salt and pepper; spread on a sheet pan and roast 12 minutes.',
      'Push potatoes aside, add salmon. Brush salmon with remaining olive oil, garlic, lemon juice; lay lemon slices on top.',
      'Roast 12–14 more minutes until salmon flakes.',
      'Scatter parsley and serve.',
    ],
    estimatedMacros: { calories: 480, protein: 34, carbs: 32, fat: 22, fiber: 5 },
  },
  {
    name: 'Coconut-Ginger Chicken Soup',
    description: 'Light, soothing, gluten-free Thai-inspired soup.',
    tags: ['gluten-free', 'dairy-free', 'low-fodmap-friendly', 'protein-rich'],
    ingredients: [
      '300 g chicken breast, sliced',
      '1 can (400 ml) coconut milk',
      '500 ml chicken broth',
      '2 tbsp grated ginger',
      '2 tbsp fish sauce',
      '1 tbsp lime juice',
      '100 g shiitake mushrooms, sliced',
      '2 spring onions, sliced',
      'Fresh cilantro',
    ],
    instructions: [
      'Bring broth, coconut milk and ginger to a gentle simmer.',
      'Add chicken; simmer 8 minutes.',
      'Add mushrooms; simmer 3 more minutes.',
      'Off heat, stir in fish sauce and lime juice. Taste.',
      'Top with spring onion and cilantro.',
    ],
    estimatedMacros: { calories: 420, protein: 30, carbs: 14, fat: 28, fiber: 3 },
  },
  {
    name: 'Quinoa, Roasted Veg & Tahini Bowl',
    description: 'A high-fibre vegetarian bowl that holds up cold for lunch the next day.',
    tags: ['gluten-free', 'dairy-free', 'vegetarian', 'fiber-rich'],
    ingredients: [
      '150 g dry quinoa',
      '1 zucchini, sliced',
      '1 red bell pepper, sliced',
      '1 carrot, sliced',
      '200 g chickpeas, drained',
      '2 tbsp olive oil',
      '1 tsp cumin',
      '2 tbsp tahini',
      '1 tbsp lemon juice',
      '2 tbsp warm water',
      'Salt and pepper',
    ],
    instructions: [
      'Cook quinoa per package directions (about 15 minutes).',
      'Toss vegetables and chickpeas with olive oil, cumin, salt; roast at 220 °C for 20 minutes.',
      'Whisk tahini, lemon juice and warm water until pourable.',
      'Build bowls with quinoa, roasted veg, drizzle of tahini.',
    ],
    estimatedMacros: { calories: 510, protein: 17, carbs: 68, fat: 19, fiber: 12 },
  },
  {
    name: 'Banana-Oat Pancakes',
    description: 'Three-ingredient base, no added sugar, gluten-free if using certified oats.',
    tags: ['gluten-free', 'vegetarian', 'fiber-rich', 'breakfast'],
    ingredients: [
      '2 ripe bananas',
      '2 eggs',
      '100 g rolled oats',
      '1 tsp cinnamon',
      '1 tsp baking powder',
      'Butter or coconut oil for the pan',
    ],
    instructions: [
      'Blend bananas, eggs, oats, cinnamon and baking powder until smooth.',
      'Heat a non-stick pan with a knob of butter over medium-low.',
      'Cook 1/4-cup pancakes 2 minutes per side.',
      'Serve with yogurt and fresh fruit.',
    ],
    estimatedMacros: { calories: 360, protein: 14, carbs: 55, fat: 9, fiber: 7 },
  },
  {
    name: 'Lentil & Vegetable Soup',
    description: 'Pantry-friendly, high-fibre, freezes well.',
    tags: ['vegetarian', 'dairy-free', 'fiber-rich', 'gluten-free'],
    ingredients: [
      '200 g dry brown lentils',
      '1 onion, diced',
      '2 carrots, diced',
      '2 celery stalks, diced',
      '2 garlic cloves, minced',
      '1 can (400 g) chopped tomatoes',
      '1.2 L vegetable broth',
      '1 tsp cumin',
      '1 tsp smoked paprika',
      'Olive oil, salt, pepper',
      'Lemon wedges to serve',
    ],
    instructions: [
      'Sauté onion, carrot, celery in olive oil 6 minutes; add garlic and spices, 30 seconds.',
      'Add lentils, tomatoes, broth.',
      'Simmer 30–35 minutes until lentils are tender.',
      'Season, finish with lemon.',
    ],
    estimatedMacros: { calories: 320, protein: 17, carbs: 52, fat: 4, fiber: 14 },
  },
  {
    name: 'Greek Chicken & Cucumber Bowl',
    description: 'Mediterranean lunch bowl with yogurt and herbs.',
    tags: ['dairy', 'protein-rich', 'low-carb', 'mediterranean'],
    ingredients: [
      '300 g chicken thighs',
      '1 tsp dried oregano',
      '1 tbsp olive oil',
      '1 lemon, zested and juiced',
      '1 cucumber, diced',
      '150 g cherry tomatoes, halved',
      '50 g feta cheese',
      '4 tbsp Greek yogurt',
      'Fresh dill',
    ],
    instructions: [
      'Marinate chicken in olive oil, oregano, lemon zest, salt 15 minutes.',
      'Sear chicken in a hot pan 6 minutes per side; rest, slice.',
      'Combine cucumber, tomato, feta with lemon juice.',
      'Top bowls with chicken, yogurt and dill.',
    ],
    estimatedMacros: { calories: 460, protein: 35, carbs: 14, fat: 28, fiber: 3 },
  },
  {
    name: 'Overnight Chia Pudding',
    description: 'High-fibre, dairy-free breakfast prepped in 5 minutes the night before.',
    tags: ['dairy-free', 'gluten-free', 'fiber-rich', 'breakfast', 'vegetarian'],
    ingredients: [
      '3 tbsp chia seeds',
      '250 ml almond milk',
      '1 tsp maple syrup',
      '1/2 tsp vanilla',
      'Toppings: berries, sliced almond, kiwi',
    ],
    instructions: [
      'Whisk chia, milk, syrup, vanilla in a jar.',
      'Refrigerate 6+ hours.',
      'Stir, top with fruit and nuts.',
    ],
    estimatedMacros: { calories: 290, protein: 8, carbs: 26, fat: 16, fiber: 14 },
  },
  {
    name: 'Turmeric Rice with Roasted Cauliflower',
    description: 'Anti-inflammatory weeknight side or vegetarian main.',
    tags: ['vegetarian', 'dairy-free', 'gluten-free', 'anti-inflammatory'],
    ingredients: [
      '200 g basmati rice',
      '1 head cauliflower, florets',
      '1 tsp turmeric',
      '1 tsp cumin',
      '2 tbsp olive oil',
      '1 lemon, juiced',
      'Handful of parsley',
      'Salt and pepper',
    ],
    instructions: [
      'Rinse rice; cook with 400 ml water + 1/2 tsp turmeric + salt, 12 minutes covered.',
      'Toss cauliflower with olive oil, remaining turmeric, cumin, salt; roast at 220 °C 22 minutes.',
      'Fluff rice, top with cauliflower, lemon juice, parsley.',
    ],
    estimatedMacros: { calories: 410, protein: 10, carbs: 70, fat: 11, fiber: 7 },
  },
  {
    name: 'Black Bean & Sweet Potato Tacos',
    description: 'Plant-forward tacos with smoky black beans and lime slaw.',
    tags: ['vegetarian', 'gluten-free', 'fiber-rich', 'dairy-free', 'mexican'],
    ingredients: [
      '1 large sweet potato, diced',
      '1 can (400 g) black beans, drained',
      '1 tsp smoked paprika',
      '1 tsp cumin',
      '8 corn tortillas',
      '200 g shredded cabbage',
      '1 lime, juiced',
      'Fresh cilantro',
      'Olive oil',
    ],
    instructions: [
      'Roast sweet potato with olive oil, paprika, cumin at 220 °C for 22 minutes.',
      'Warm black beans in a small pan, mash lightly.',
      'Toss cabbage with lime juice and salt.',
      'Warm tortillas; build tacos with beans, sweet potato, slaw, cilantro.',
    ],
    estimatedMacros: { calories: 430, protein: 15, carbs: 78, fat: 9, fiber: 16 },
  },
  {
    name: 'Roasted Tomato Soup with White Beans',
    description: 'Roasting deepens the flavour; cannellini beans add body without cream.',
    tags: ['vegetarian', 'dairy-free', 'gluten-free', 'fiber-rich'],
    ingredients: [
      '1 kg ripe tomatoes, halved',
      '1 onion, quartered',
      '4 garlic cloves',
      '2 tbsp olive oil',
      '1 can (400 g) cannellini beans, drained',
      '300 ml vegetable broth',
      'Basil leaves',
      'Salt, pepper, pinch of chili flakes',
    ],
    instructions: [
      'Roast tomato, onion, garlic with olive oil, salt at 220 °C for 30 minutes.',
      'Blend with beans and broth until smooth.',
      'Reheat; finish with basil and chili.',
    ],
    estimatedMacros: { calories: 320, protein: 12, carbs: 44, fat: 10, fiber: 11 },
  },
  {
    name: 'Beef & Broccoli Stir-fry (gluten-free)',
    description: 'Uses tamari instead of soy sauce for a gluten-free hit.',
    tags: ['gluten-free', 'dairy-free', 'protein-rich', 'asian'],
    ingredients: [
      '300 g flank steak, thinly sliced',
      '300 g broccoli florets',
      '2 tbsp tamari',
      '1 tbsp rice vinegar',
      '1 tbsp grated ginger',
      '2 garlic cloves',
      '1 tsp cornstarch',
      '1 tbsp sesame oil',
      'Cooked rice to serve',
    ],
    instructions: [
      'Whisk tamari, vinegar, ginger, garlic, cornstarch.',
      'Sear steak in sesame oil 90 seconds; remove.',
      'Stir-fry broccoli 3 minutes with 2 tbsp water; return steak; add sauce.',
      'Toss until glossy. Serve over rice.',
    ],
    estimatedMacros: { calories: 470, protein: 34, carbs: 38, fat: 18, fiber: 5 },
  },
  {
    name: 'Apple-Cinnamon Oatmeal',
    description: 'Cozy, fibre-rich breakfast bowl.',
    tags: ['vegetarian', 'fiber-rich', 'breakfast'],
    ingredients: [
      '60 g rolled oats',
      '300 ml milk of choice',
      '1 apple, diced',
      '1 tsp cinnamon',
      '1 tbsp maple syrup',
      '1 tbsp almond butter',
      'Pinch of salt',
    ],
    instructions: [
      'Simmer oats, milk, half the apple, cinnamon, salt 6 minutes.',
      'Sweeten with maple, swirl in almond butter.',
      'Top with remaining apple.',
    ],
    estimatedMacros: { calories: 380, protein: 11, carbs: 60, fat: 11, fiber: 9 },
  },
  {
    name: 'Mediterranean Tuna Salad',
    description: 'No-cook, high-protein lunch that travels well.',
    tags: ['gluten-free', 'dairy-free', 'protein-rich', 'mediterranean', 'low-carb'],
    ingredients: [
      '2 cans tuna in olive oil, drained',
      '1 can white beans, drained',
      '100 g cherry tomatoes, halved',
      '2 tbsp olives, sliced',
      '2 tbsp red onion, minced',
      '1 lemon, juiced',
      '2 tbsp olive oil',
      'Parsley, salt, pepper',
    ],
    instructions: [
      'Combine tuna and beans in a bowl.',
      'Add tomatoes, olives, onion.',
      'Dress with lemon juice + olive oil; season; toss with parsley.',
    ],
    estimatedMacros: { calories: 410, protein: 32, carbs: 26, fat: 18, fiber: 8 },
  },
  {
    name: 'Egg & Spinach Breakfast Wrap',
    description: 'Quick protein-rich breakfast in a whole-wheat tortilla.',
    tags: ['vegetarian', 'protein-rich', 'breakfast', 'gluten'],
    ingredients: [
      '2 eggs',
      '1 handful baby spinach',
      '1 whole-wheat tortilla',
      '2 tbsp shredded cheese (optional)',
      '1 tbsp olive oil',
      'Salt and pepper',
    ],
    instructions: [
      'Wilt spinach in olive oil 1 minute.',
      'Add beaten eggs, scramble gently.',
      'Pile into tortilla with cheese; roll, slice in half.',
    ],
    estimatedMacros: { calories: 380, protein: 22, carbs: 28, fat: 18, fiber: 4 },
  },
  {
    name: 'Roasted Chickpeas',
    description: 'Crunchy plant-based snack — replace chips or croutons.',
    tags: ['vegetarian', 'dairy-free', 'gluten-free', 'fiber-rich', 'snack'],
    ingredients: [
      '1 can (400 g) chickpeas, drained, dried',
      '1 tbsp olive oil',
      '1 tsp paprika',
      '1/2 tsp garlic powder',
      'Salt',
    ],
    instructions: [
      'Toss chickpeas with oil and spices.',
      'Spread on a sheet pan; roast at 220 °C for 25 minutes, shaking once.',
      'Cool 5 minutes for max crunch.',
    ],
    estimatedMacros: { calories: 220, protein: 10, carbs: 28, fat: 8, fiber: 9 },
  },
  {
    name: 'Zucchini Noodles with Turkey Bolognese',
    description: 'A low-carb version of a comfort classic.',
    tags: ['gluten-free', 'low-carb', 'protein-rich', 'dairy-free'],
    ingredients: [
      '4 medium zucchinis, spiralized',
      '300 g ground turkey',
      '1 onion, diced',
      '2 garlic cloves',
      '1 can (400 g) crushed tomatoes',
      '1 tsp oregano',
      '1 tbsp olive oil',
      'Salt, pepper, chili flakes',
    ],
    instructions: [
      'Sauté onion in olive oil 4 minutes; add garlic 30 sec.',
      'Add turkey, brown 5 minutes.',
      'Add tomatoes, oregano, salt; simmer 12 minutes.',
      'Toss with raw zucchini noodles off heat for 1 minute, serve.',
    ],
    estimatedMacros: { calories: 360, protein: 30, carbs: 22, fat: 16, fiber: 6 },
  },
  {
    name: 'Cauliflower Soup with Toasted Almonds',
    description: 'Silky, creamy without cream.',
    tags: ['dairy-free', 'gluten-free', 'vegetarian', 'low-carb'],
    ingredients: [
      '1 head cauliflower, florets',
      '1 onion, diced',
      '2 garlic cloves',
      '700 ml vegetable broth',
      '2 tbsp olive oil',
      '30 g sliced almonds, toasted',
      'Salt, pepper, pinch of nutmeg',
    ],
    instructions: [
      'Sauté onion in olive oil 5 minutes; add garlic 30 seconds.',
      'Add cauliflower and broth; simmer 18 minutes.',
      'Blend until silky; season with nutmeg, salt.',
      'Top with toasted almonds.',
    ],
    estimatedMacros: { calories: 220, protein: 7, carbs: 18, fat: 14, fiber: 6 },
  },
  {
    name: 'Salmon Poke Bowl',
    description: 'Fresh, fast, customizable. Use sushi-grade fish.',
    tags: ['gluten-free', 'dairy-free', 'protein-rich', 'omega-3'],
    ingredients: [
      '200 g sushi-grade salmon, diced',
      '150 g cooked sushi rice',
      '1 avocado, sliced',
      '1 cucumber, diced',
      '1 carrot, julienned',
      '2 tbsp tamari',
      '1 tsp sesame oil',
      '1 tsp rice vinegar',
      'Pickled ginger, sesame seeds',
    ],
    instructions: [
      'Toss salmon with tamari, sesame oil, vinegar.',
      'Build the bowl with rice, salmon, cucumber, carrot, avocado.',
      'Top with ginger and sesame.',
    ],
    estimatedMacros: { calories: 540, protein: 30, carbs: 50, fat: 24, fiber: 6 },
  },
  {
    name: 'Mushroom & Spinach Frittata',
    description: 'Make once, eat through the week.',
    tags: ['vegetarian', 'protein-rich', 'gluten-free', 'low-carb', 'breakfast'],
    ingredients: [
      '8 eggs',
      '200 g mushrooms, sliced',
      '100 g baby spinach',
      '1 onion, diced',
      '50 g feta or goat cheese',
      '2 tbsp olive oil',
      'Salt, pepper',
    ],
    instructions: [
      'Sauté onion in olive oil 4 minutes; add mushrooms, 6 minutes.',
      'Wilt spinach in, 1 minute.',
      'Pour over beaten, seasoned eggs; crumble cheese on top.',
      'Bake at 190 °C for 18–20 minutes until set.',
    ],
    estimatedMacros: { calories: 320, protein: 22, carbs: 8, fat: 22, fiber: 2 },
  },
  {
    name: 'Berry & Yogurt Parfait',
    description: 'Five-minute breakfast or snack.',
    tags: ['dairy', 'protein-rich', 'fiber-rich', 'breakfast'],
    ingredients: [
      '200 g Greek yogurt',
      '150 g mixed berries',
      '30 g granola',
      '1 tbsp honey (optional)',
      '1 tbsp chia seeds',
    ],
    instructions: [
      'Layer yogurt, berries, granola in a glass twice.',
      'Top with chia and honey.',
    ],
    estimatedMacros: { calories: 320, protein: 20, carbs: 42, fat: 8, fiber: 8 },
  },
  {
    name: 'Miso-Ginger Tofu Stir-fry',
    description: 'Plant-based dinner with deep umami.',
    tags: ['vegetarian', 'gluten-free', 'dairy-free', 'protein-rich'],
    ingredients: [
      '400 g firm tofu, cubed',
      '200 g bok choy',
      '150 g shiitake mushrooms',
      '2 tbsp white miso',
      '1 tbsp tamari',
      '1 tbsp rice vinegar',
      '1 tbsp grated ginger',
      '1 tbsp sesame oil',
      'Cooked rice or noodles',
    ],
    instructions: [
      'Sear tofu in sesame oil until golden, 6 minutes.',
      'Whisk miso, tamari, vinegar, ginger with 60 ml water.',
      'Add mushrooms, then bok choy; pour sauce, toss 2 minutes.',
      'Serve over rice or noodles.',
    ],
    estimatedMacros: { calories: 420, protein: 26, carbs: 38, fat: 18, fiber: 6 },
  },
  {
    name: 'White Bean & Rosemary Mash',
    description: 'A creamy plant-based side, ready in 10 minutes.',
    tags: ['vegetarian', 'dairy-free', 'gluten-free', 'fiber-rich'],
    ingredients: [
      '2 cans (400 g each) white beans, drained',
      '2 garlic cloves',
      '2 tbsp olive oil',
      '1 sprig fresh rosemary',
      'Juice of 1/2 lemon',
      'Salt, pepper',
    ],
    instructions: [
      'Warm olive oil with garlic and rosemary 2 minutes; remove rosemary.',
      'Add beans and 2 tbsp water; mash with a fork to desired texture.',
      'Stir in lemon, season.',
    ],
    estimatedMacros: { calories: 260, protein: 13, carbs: 32, fat: 9, fiber: 9 },
  },
  {
    name: 'Sheet-pan Roast Chicken with Lemon and Herbs',
    description: 'Whole chicken thighs and root veg with very little cleanup.',
    tags: ['gluten-free', 'dairy-free', 'protein-rich'],
    ingredients: [
      '6 bone-in chicken thighs',
      '500 g baby potatoes, halved',
      '2 carrots, chunked',
      '2 lemons, sliced',
      '4 garlic cloves',
      '2 tbsp olive oil',
      '1 tsp dried thyme',
      'Salt, pepper',
    ],
    instructions: [
      'Toss everything on a sheet pan with olive oil, thyme, salt.',
      'Roast at 220 °C for 40 minutes until chicken is 75 °C internal.',
      'Rest 5 minutes; serve.',
    ],
    estimatedMacros: { calories: 520, protein: 36, carbs: 30, fat: 26, fiber: 5 },
  },
  {
    name: 'Spiced Carrot & Lentil Soup',
    description: 'Warming, high-fibre, freezer-friendly.',
    tags: ['vegetarian', 'dairy-free', 'gluten-free', 'fiber-rich'],
    ingredients: [
      '300 g carrots, sliced',
      '200 g red lentils, rinsed',
      '1 onion, diced',
      '1 tbsp grated ginger',
      '1 tsp cumin',
      '1 tsp coriander',
      '1 L vegetable broth',
      '2 tbsp olive oil',
      'Lemon, parsley to finish',
    ],
    instructions: [
      'Sauté onion in olive oil 5 minutes; add ginger and spices, 30 sec.',
      'Add carrots, lentils, broth; simmer 25 minutes.',
      'Blend smooth; season; finish with lemon and parsley.',
    ],
    estimatedMacros: { calories: 320, protein: 14, carbs: 50, fat: 6, fiber: 11 },
  },
  {
    name: 'Greek Yogurt Chicken Salad',
    description: 'Lighter than mayo-based, still creamy.',
    tags: ['dairy', 'protein-rich', 'low-carb'],
    ingredients: [
      '300 g cooked chicken, shredded',
      '4 tbsp Greek yogurt',
      '1 tbsp Dijon mustard',
      '1 celery stalk, diced',
      '2 tbsp red onion, minced',
      '1 tbsp lemon juice',
      'Fresh dill, salt, pepper',
    ],
    instructions: [
      'Whisk yogurt, mustard, lemon juice.',
      'Fold in chicken, celery, onion, dill.',
      'Chill 10 minutes; serve in lettuce cups or on toast.',
    ],
    estimatedMacros: { calories: 340, protein: 38, carbs: 6, fat: 18, fiber: 1 },
  },
  {
    name: 'Pumpkin & Coconut Curry',
    description: 'Hearty vegan curry with chickpeas and pumpkin.',
    tags: ['vegan', 'dairy-free', 'gluten-free', 'fiber-rich', 'spicy'],
    ingredients: [
      '500 g pumpkin or butternut squash, cubed',
      '1 can (400 g) chickpeas, drained',
      '1 can (400 ml) coconut milk',
      '2 tbsp Thai red curry paste',
      '1 onion, diced',
      '2 garlic cloves',
      '200 g spinach',
      '1 tbsp lime juice',
      'Cooked rice to serve',
    ],
    instructions: [
      'Sauté onion in oil 5 minutes; add garlic, curry paste, 1 minute.',
      'Add pumpkin and coconut milk; simmer 18 minutes.',
      'Add chickpeas, then spinach until wilted.',
      'Finish with lime; serve over rice.',
    ],
    estimatedMacros: { calories: 460, protein: 14, carbs: 52, fat: 22, fiber: 11 },
  },
  {
    name: 'Avocado Toast with Egg',
    description: 'A classic breakfast — protein + healthy fats.',
    tags: ['vegetarian', 'protein-rich', 'breakfast', 'gluten'],
    ingredients: [
      '2 slices sourdough',
      '1 avocado',
      '2 eggs',
      'Lemon juice',
      'Chili flakes, salt, pepper',
    ],
    instructions: [
      'Toast bread.',
      'Mash avocado with lemon juice and salt; spread on toast.',
      'Cook eggs as desired; place on top.',
      'Finish with chili flakes and pepper.',
    ],
    estimatedMacros: { calories: 460, protein: 18, carbs: 40, fat: 24, fiber: 9 },
  },
  {
    name: 'Cucumber, Tomato & Chickpea Salad',
    description: 'A 10-minute side or light lunch.',
    tags: ['vegan', 'vegetarian', 'gluten-free', 'dairy-free', 'fiber-rich'],
    ingredients: [
      '1 cucumber, diced',
      '200 g cherry tomatoes, halved',
      '1 can chickpeas, drained',
      '2 tbsp red onion, minced',
      '2 tbsp olive oil',
      '1 tbsp red-wine vinegar',
      '1 tsp dried oregano',
      'Salt, pepper',
    ],
    instructions: [
      'Combine vegetables and chickpeas.',
      'Whisk olive oil, vinegar, oregano, salt, pepper.',
      'Toss; rest 10 minutes before serving.',
    ],
    estimatedMacros: { calories: 290, protein: 10, carbs: 30, fat: 14, fiber: 8 },
  },
  {
    name: 'Soft Polenta with Mushroom Ragù',
    description: 'Restaurant feel from very pantry ingredients.',
    tags: ['vegetarian', 'gluten-free', 'comfort-food'],
    ingredients: [
      '150 g polenta',
      '600 ml water or broth',
      '30 g butter',
      '40 g grated parmesan',
      '400 g mixed mushrooms, sliced',
      '1 shallot, minced',
      '2 garlic cloves',
      '1 tbsp tomato paste',
      '150 ml red wine or extra broth',
      'Olive oil, thyme, salt',
    ],
    instructions: [
      'Whisk polenta into simmering liquid; cook 20 minutes, stirring; finish with butter + parm.',
      'Sear mushrooms in olive oil 6 minutes; add shallot, garlic 1 minute.',
      'Stir in tomato paste, then wine; reduce 3 minutes; season.',
      'Spoon ragù over polenta.',
    ],
    estimatedMacros: { calories: 460, protein: 14, carbs: 60, fat: 16, fiber: 5 },
  },
];

let cache: Recipe[] | null = null;

export function getCuratedRecipes(): Recipe[] {
  if (cache) return cache;
  cache = CURATED.map((r, idx) => ({
    id: `curated-recipe-${idx + 1}`,
    name: r.name,
    description: r.description,
    ingredients: r.ingredients,
    instructions: r.instructions,
    tags: r.tags,
    estimatedMacros: r.estimatedMacros,
    sourceName: 'Curated',
    sourceUrl: undefined,
  }));
  return cache;
}
